-- MySQL Script generated by MySQL Workbench
-- Fri May 15 15:42:18 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_bemestar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_bemestar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_bemestar` DEFAULT CHARACTER SET utf8 ;
USE `db_bemestar` ;

-- -----------------------------------------------------
-- Table `db_bemestar`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bemestar`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `us_nome` VARCHAR(100) NOT NULL,
  `us_datanasc` DATE NOT NULL,
  `us_email` VARCHAR(100) NOT NULL,
  `us_cpf` VARCHAR(14) NOT NULL,
  `us_telefone` VARCHAR(20) NOT NULL,
  `us_senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `us_cpf_UNIQUE` (`us_cpf` ASC) VISIBLE,
  UNIQUE INDEX `us_email_UNIQUE` (`us_email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bemestar`.`medicamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bemestar`.`medicamentos` (
  `id_medicamento` INT NOT NULL AUTO_INCREMENT,
  `medicam_nome` VARCHAR(255) NOT NULL,
  `medicam_tipo` VARCHAR(100) NOT NULL,
  `medicam_descricao` TEXT NOT NULL,
  `medicam_dosagem` VARCHAR(50) NOT NULL,
  `medicam_fabric` VARCHAR(150) NOT NULL,
  `medicam_via_administracao` VARCHAR(50) NOT NULL,
  `medicam_dados_regulatório_anvisa` VARCHAR(50) NOT NULL,
  `medicam_valid_lote` DATE NOT NULL,
  `medicam_valor_unit` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_medicamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bemestar`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bemestar`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `end_rua` VARCHAR(50) NOT NULL,
  `end_bairro` VARCHAR(50) NOT NULL,
  `end_cidade` VARCHAR(50) NOT NULL,
  `end_estado` VARCHAR(2) NOT NULL,
  `end_cep` VARCHAR(10) NOT NULL,
  `end_complemento` VARCHAR(100) NULL DEFAULT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `fk_idusuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_bemestar`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bemestar`.`carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bemestar`.`carrinho` (
  `id_carrinho` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_carrinho`),
  INDEX `fk_id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_carrinho_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_bemestar`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bemestar`.`item_carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bemestar`.`item_carrinho` (
  `id_item_carrinho` INT NOT NULL AUTO_INCREMENT,
  `id_carrinho` INT NOT NULL,
  `id_medicamento` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`id_item_carrinho`),
  INDEX `fk_id_carrinho_idx` (`id_carrinho` ASC) VISIBLE,
  INDEX `fk_id_medicamento_idx` (`id_medicamento` ASC) VISIBLE,
  CONSTRAINT `fk_item_carrinho_carrinho`
    FOREIGN KEY (`id_carrinho`)
    REFERENCES `db_bemestar`.`carrinho` (`id_carrinho`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_carrinho_medicamento`
    FOREIGN KEY (`id_medicamento`)
    REFERENCES `db_bemestar`.`medicamentos` (`id_medicamento`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bemestar`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bemestar`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `data_pedido` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `pedido_status` VARCHAR(20) NOT NULL,
  `valor_total` DECIMAL(10,2) NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_endereco` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_id_endereco_idx` (`id_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_bemestar`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_endereco`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `db_bemestar`.`endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bemestar`.`item_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bemestar`.`item_pedido` (
  `id_item` INT NOT NULL AUTO_INCREMENT,
  `item_quantidade` INT NOT NULL,
  `preco_unit` DECIMAL(10,2) NOT NULL,
  `id_pedido` INT NOT NULL,
  `id_medicamento` INT NOT NULL,
  PRIMARY KEY (`id_item`),
  INDEX `fk_id_pedido_idx` (`id_pedido` ASC) VISIBLE,
  INDEX `fk_id_medicamento_idx` (`id_medicamento` ASC) VISIBLE,
  CONSTRAINT `fk_item_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `db_bemestar`.`pedido` (`id_pedido`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_medicamento`
    FOREIGN KEY (`id_medicamento`)
    REFERENCES `db_bemestar`.`medicamentos` (`id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
